server:
    port: 8000

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/2206?serverTimezone=GMT%2b8
        username: root
        password: root
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

# mybatis
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: cn.jasonone.model.bean
    configuration:
        map-underscore-to-camel-case: true

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
    # token名称 (同时也是cookie名称)
    token-name: hm-token
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: true
    # token风格
    token-style: uuid
    # 是否输出操作日志
    is-log: false

# rabbitmq配置
---
spring:
    rabbitmq:
        host: localhost
        port: 5672

# 邮箱配置
---
spring:
    mail:
        host: smtp.exmail.qq.com
        username: hongmao@jasonone.cn
        password: Hm@qwe01
#        properties:
#            mail.smtp.ssl.enable: true
#        port: 465
# redis配置
---
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  elasticsearch:
    rest:
      uris: http://localhost:9200
# es 配置
# pagehelper
pagehelper:
    helper-dialect: mysql
    page-size-zero: true
    reasonable: true
logging:
    level:
      cn.jasonone.mapper: trace
